#!/usr/bin/env node

var server = require('http').createServer(httpHandler),
    spawn = require('child_process').spawn,
    exec = require('child_process').exec,
    io = require('socket.io').listen(server),
    send = require('send'),
    server,
    socket;

server.listen(8090);

function httpHandler(req, res) {
  switch(req.method)
  {
    case 'GET':
      // Files that must be served from the package directory
      var package_urls = ["/", "/index.html", "/node_modules/docter/ghf_marked.css"];

      var source;
      // If not a package file then serve it from the execution directory
      if (package_urls.indexOf(req.url) === -1) {
        source = process.cwd();
      } else {
        source = __dirname;
      }

      send(req, req.url)
        .root(source)
        .pipe(res);
      break;

    // case 'HEAD':
      // res.writeHead(200);
      // res.end();
      // exec('open -g http://localhost:8090', function(error, stdout, stderr){
        // http.request({port: 8090})
      // });
      // break;

    case 'DELETE':
      socket.emit('die');
      process.exit();
      break;

    case 'PUT':
      var newHTML = '';
      var gfm = spawn(__dirname + '/node_modules/docter/bin/github-flavored-markdown.rb', ['--unstyled']);
      req.on('data', function(chunk){
        gfm.stdin.write(chunk);
      });
      req.on('end', function(){
        gfm.stdin.end();
        res.writeHead(200);
        res.end();
      });
      gfm.stdout.on('data', function(data) {
        newHTML += data;
      });
      gfm.on('exit',function(ecode){
        socket.emit('newContent', newHTML);
      });
      break;

    default:
  }
}

io.set('log level', 1);
io.sockets.on('connection', function(sock){
  socket = sock;
  //process.stdout.write('connection established!');

  var newHTML = '';
  var gfm = spawn(__dirname + '/node_modules/docter/bin/github-flavored-markdown.rb', ['--unstyled']);
  process.stdin.on('data', function(chunk){
    gfm.stdin.write(chunk);
  });
  process.stdin.on('end', function(){
    gfm.stdin.end();
  });
  gfm.stdout.on('data', function(data) {
    newHTML += data;
  });
  gfm.on('exit',function(ecode){
    socket.emit('newContent', newHTML);
  });
  process.stdin.resume();
});


if (process.platform.toLowerCase().indexOf('darwin') >= 0){
  exec('open -g http://localhost:8090', function(error, stdout, stderr){});
}
else {  // assume unix/linux
  exec('xdg-open http://localhost:8090', function(error, stdout, stderr){});
}
