#!/usr/bin/env node

var server = require('http').createServer(httpHandler),
    spawn = require('child_process').spawn,
    exec = require('child_process').exec,
    io = require('socket.io').listen(server),
    fs = require('fs'),
    server,
    socket;

server.listen(8090);

function httpHandler(req, res) {
  process.stdout.write(req.method + "\n");
  switch(req.method)
  {
    case 'GET':
      fs.readFile(__dirname + '/instant-markdown.html', function(err, data){
        res.writeHead(200);
        res.end(data);
      });
      break;

    case 'HEAD':
      res.writeHead(200);
      res.end();
      exec('open -g http://localhost:8090',
        function(error, stdout, stderr){
        
      });
      break;

    case 'DELETE':
      socket.emit('die');
      process.exit();
      break;

    case 'PUT':
      var gfm = spawn('gfm');
      gfm.stdout.on('data', function(data) {
        io.write(data);
      });
      // gfm.on('exit',function(ecode){
        // 
      // });
      break;

    default:
  }
}

io.sockets.on('connection', function(sock){
  socket = sock;
  process.stdout.write('connection established!');
});








// process.stderr.on('data',function(err) {
	// process.stdout.write('ERR: '+err);
// })

// process.stdin.resume();
// process.stdin.setEncoding('utf8');

// process.stdin.on('data', function (chunk) {
	// gfm.stdin.write(chunk);
	// gfm.stdin.end();
// });
