name: Node.js

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 12
          - 14
          - 16
        include:
          - os: windows-latest
            node_version: 14
          - os: macos-latest
            node_version: 14

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: npm install

    - name: Link globally on POSIX
      run: sudo npm link
      if: ${{ matrix.os != 'windows-latest' }}

    - name: Link globally on Windows
      run: npm link
      if: ${{ matrix.os == 'windows-latest' }}

    - name: Integration test
      run: |
        npx --no-install instant-markdown-d --version
        npm test &
        sleep 5
        npm stop
      env:
        CI: true

    - name: Install mamba
      uses: mamba-org/setup-micromamba@v1.4.4
      with:
        micromamba-version: '1.5.1-0'
        environment-file: tests/environment.yml
        cache-environment: true
        cache-downloads: true
        init-shell: >-
          bash
          zsh
          cmd.exe
          powershell

    - name: Fine grained tests
      run: |
        python -m pytest
